import { useState, useRef, useEffect, useCallback } from "react";
import { saveRecording } from "../services/db";
import fixWebmDuration from "fix-webm-duration";
import { loadSettings } from "../services/settings";

const QUALITY_MAP = {
  "720p": { width: 1280, height: 720, bitrate: 6_000_000 },
  "1080p": { width: 1920, height: 1080, bitrate: 12_000_000 },
  "4K": { width: 3840, height: 2160, bitrate: 28_000_000 },
};

function formatTime(secs) {
  const h = Math.floor(secs / 3600).toString().padStart(2, "0");
  const m = Math.floor((secs % 3600) / 60).toString().padStart(2, "0");
  const s = (secs % 60).toString().padStart(2, "0");
  return `${h}:${m}:${s}`;
}

function formatBytes(bytes) {
  if (bytes < 1024 * 1024) return `${(bytes / 1024).toFixed(1)} KB`;
  return `${(bytes / (1024 * 1024)).toFixed(1)} MB`;
}

/** Pick the best supported MIME type for MediaRecorder based on presence of audio tracks. */
function getBestMimeType(hasAudio = true) {
  const candidatesWithAudio = [
    "video/webm;codecs=vp9,opus",
    "video/webm;codecs=vp8,opus",
    "video/webm",
  ];
  const candidatesVideoOnly = [
    "video/webm;codecs=vp9",
    "video/webm;codecs=vp8",
    "video/webm",
  ];
  const candidates = hasAudio ? candidatesWithAudio : candidatesVideoOnly;
  for (const mime of candidates) {
    if (MediaRecorder.isTypeSupported(mime)) return mime;
  }
  return "";
}

/**
 * EBML Duration Fixer for WebM files generated by Chrome MediaRecorder.
 *
 * ROOT CAUSE OF 1–2 SECOND BUG (CONFIRMED):
 * Chrome's MediaRecorder always writes a nonzero Duration (e.g. 1000–2000ms) into the
 * EBML Info Header when recording stops. The fix-webm-duration npm library checks:
 *   if (existingDuration > 0) return false;  ← skips patching!
 * So a 10-second recording keeps Chrome's wrong 1–2s header duration.
 *
 * FIX A: Force-write the correct Duration float directly via DataView, bypassing the
 * npm library's nonzero-duration guard entirely.
 *
 * FIX B: If Chrome omitted the Duration element (streaming/live mode), inject it into
 * the EBML Info block by rebuilding the buffer.
 *
 * Duration stored in file = durationMs (when timecodeScale = 1,000,000 ns = 1ms/tick).
 */
function getWebmDurationFromClusters(arrayBuffer) {
  const bytes = new Uint8Array(arrayBuffer);

  // Reads EBML variable-length integer (VINT) for SIZE fields — strips marker bit
  function readVint(offset) {
    if (offset >= bytes.length) return null;
    const first = bytes[offset];
    if (first === 0) return null; // invalid
    let mask = 0x80;
    let length = 1;
    while (mask > 0 && (first & mask) === 0) {
      mask >>= 1;
      length++;
    }
    if (length > 8 || offset + length > bytes.length) return null;
    // Check for unknown-size sentinel (all data bits are 1)
    let isUnknown = (first & (mask - 1)) === (mask - 1);
    for (let i = 1; i < length && isUnknown; i++) {
      if (bytes[offset + i] !== 0xFF) isUnknown = false;
    }
    let value = first & (mask - 1);
    for (let i = 1; i < length; i++) {
      value = (value * 256) + bytes[offset + i];
    }
    return { value, length, isUnknown };
  }

  // Reads EBML Element ID — keeps marker bit (EBML IDs include their marker bits)
  function readId(offset) {
    if (offset >= bytes.length) return null;
    const first = bytes[offset];
    if (first === 0) return null;
    let mask = 0x80;
    let length = 1;
    while (mask > 0 && (first & mask) === 0) {
      mask >>= 1;
      length++;
    }
    if (length > 8 || offset + length > bytes.length) return null;
    let id = 0;
    for (let i = 0; i < length; i++) {
      id = (id * 256) + bytes[offset + i];
    }
    return { id, length };
  }

  let offset = 0;
  let lastTimecode = 0;
  let lastBlockOffset = 0;

  // 1. Parse EBML Header
  const headerId = readId(offset);
  if (!headerId) return 0;
  offset += headerId.length;
  const headerSize = readVint(offset);
  if (!headerSize) return 0;
  offset += headerSize.length + headerSize.value;

  // 2. Parse Segment
  const segmentId = readId(offset);
  if (!segmentId || segmentId.id !== 0x18538067) return 0;
  offset += segmentId.length;
  const segmentSize = readVint(offset);
  if (!segmentSize) return 0;
  offset += segmentSize.length;

  const segmentEnd = segmentSize.isUnknown ? bytes.length : Math.min(offset + segmentSize.value, bytes.length);

  let lastClusterOffset = -1;
  let lastClusterSize = 0;

  // 3. Scan inside Segment for Clusters
  while (offset < segmentEnd && offset < bytes.length - 4) {
    const idInfo = readId(offset);
    if (!idInfo) break;
    offset += idInfo.length;
    const sizeInfo = readVint(offset);
    if (!sizeInfo) break;
    offset += sizeInfo.length;

    // Cluster ID: 0x1F43B675
    if (idInfo.id === 0x1F43B675) {
      lastClusterOffset = offset;
      lastClusterSize = sizeInfo.value;
    }

    if (sizeInfo.isUnknown) break;
    offset += sizeInfo.value;
  }

  // 4. Parse only the last Cluster content to find Timecode and max Block offset
  if (lastClusterOffset !== -1) {
    let clusterOffset = lastClusterOffset;
    const clusterEnd = Math.min(clusterOffset + lastClusterSize, bytes.length);

    while (clusterOffset < clusterEnd && clusterOffset < bytes.length - 4) {
      const itemId = readId(clusterOffset);
      if (!itemId) break;
      clusterOffset += itemId.length;
      const itemSize = readVint(clusterOffset);
      if (!itemSize) break;
      clusterOffset += itemSize.length;

      // Timecode ID: 0xE7
      if (itemId.id === 0xE7) {
        let tc = 0;
        for (let k = 0; k < itemSize.value; k++) {
          tc = (tc * 256) + bytes[clusterOffset + k];
        }
        lastTimecode = tc;
      }
      // SimpleBlock ID: 0xA3
      else if (itemId.id === 0xA3) {
        const trackVal = readVint(clusterOffset);
        if (trackVal) {
          const timeOffsetStart = clusterOffset + trackVal.length;
          const timeOffset = (bytes[timeOffsetStart] << 8) | bytes[timeOffsetStart + 1];
          const signedTimeOffset = (timeOffset << 16) >> 16;
          lastBlockOffset = Math.max(lastBlockOffset, signedTimeOffset);
        }
      }
      // BlockGroup ID: 0xA0
      else if (itemId.id === 0xA0) {
        const bgEnd = clusterOffset + itemSize.value;
        let bgOffset = clusterOffset;
        while (bgOffset < bgEnd) {
          const bgItemId = readId(bgOffset);
          if (!bgItemId) break;
          bgOffset += bgItemId.length;
          const bgItemSize = readVint(bgOffset);
          if (!bgItemSize) break;
          bgOffset += bgItemSize.length;

          if (bgItemId.id === 0xA1) { // Block
            const trackVal = readVint(bgOffset);
            if (trackVal) {
              const timeOffsetStart = bgOffset + trackVal.length;
              const timeOffset = (bytes[timeOffsetStart] << 8) | bytes[timeOffsetStart + 1];
              const signedTimeOffset = (timeOffset << 16) >> 16;
              lastBlockOffset = Math.max(lastBlockOffset, signedTimeOffset);
            }
          }
          bgOffset += bgItemSize.value;
        }
      }

      clusterOffset += itemSize.value;
    }
  }

  return lastTimecode + lastBlockOffset;
}

function setWebmDuration(arrayBuffer, durationMs) {
  const bytes = new Uint8Array(arrayBuffer);
  const dataView = new DataView(arrayBuffer);

  // Reads EBML variable-length integer (VINT) for SIZE fields — strips marker bit
  function readVint(offset) {
    if (offset >= bytes.length) return null;
    const first = bytes[offset];
    if (first === 0) return null; // invalid
    let mask = 0x80;
    let length = 1;
    while (mask > 0 && (first & mask) === 0) {
      mask >>= 1;
      length++;
    }
    if (length > 8 || offset + length > bytes.length) return null;
    // Check for unknown-size sentinel (all data bits are 1)
    let isUnknown = (first & (mask - 1)) === (mask - 1);
    for (let i = 1; i < length && isUnknown; i++) {
      if (bytes[offset + i] !== 0xFF) isUnknown = false;
    }
    let value = first & (mask - 1);
    for (let i = 1; i < length; i++) {
      value = (value * 256) + bytes[offset + i];
    }
    return { value, length, isUnknown };
  }

  // Reads EBML Element ID — keeps marker bit (EBML IDs include their marker bits)
  function readId(offset) {
    if (offset >= bytes.length) return null;
    const first = bytes[offset];
    if (first === 0) return null;
    let mask = 0x80;
    let length = 1;
    while (mask > 0 && (first & mask) === 0) {
      mask >>= 1;
      length++;
    }
    if (length > 8 || offset + length > bytes.length) return null;
    let id = 0;
    for (let i = 0; i < length; i++) {
      id = (id * 256) + bytes[offset + i];
    }
    return { id, length };
  }

  function writeVint(buffer, offset, value, length) {
    let mask = 0x80;
    for (let i = 1; i < length; i++) {
      mask >>= 1;
    }
    let val = value;
    buffer[offset] = mask | (val >> ((length - 1) * 8));
    for (let i = 1; i < length; i++) {
      buffer[offset + i] = (val >> ((length - 1 - i) * 8)) & 0xFF;
    }
  }

  let offset = 0;
  let timecodeScale = 1000000; // default: 1ms/tick (Chrome always uses this)
  let durationOffset = -1;
  let durationSize = 0;
  // Track byte range of the Info block for potential Duration injection
  let infoBlockStart = -1;  // byte offset of the Info element ID
  let infoBlockEnd = -1;    // byte offset just after Info element's content
  let infoSizeLength = 0;
  let infoSizeValue = 0;

  while (offset < bytes.length - 4) {
    const idInfo = readId(offset);
    if (!idInfo) break;
    offset += idInfo.length;
    const sizeInfo = readVint(offset);
    if (!sizeInfo) break;
    offset += sizeInfo.length;

    // Segment ID: 0x18538067
    if (idInfo.id === 0x18538067) {
      // If size is unknown (streaming WebM), treat segmentEnd as bytes.length
      const segmentEnd = sizeInfo.isUnknown ? bytes.length : Math.min(offset + sizeInfo.value, bytes.length);

      while (offset < segmentEnd && offset < bytes.length - 4) {
        const segIdInfo = readId(offset);
        if (!segIdInfo) break;
        const segIdStart = offset;
        offset += segIdInfo.length;
        const segSizeInfo = readVint(offset);
        if (!segSizeInfo) break;
        offset += segSizeInfo.length;

        // Info ID: 0x1549A966
        if (segIdInfo.id === 0x1549A966) {
          infoBlockStart = segIdStart;
          infoSizeLength = segSizeInfo.length;
          infoSizeValue = segSizeInfo.value;
          const infoContentStart = offset;
          const infoEnd = segSizeInfo.isUnknown
            ? bytes.length
            : Math.min(offset + segSizeInfo.value, bytes.length);
          infoBlockEnd = infoEnd;

          while (offset < infoEnd && offset < bytes.length - 4) {
            const infoIdInfo = readId(offset);
            if (!infoIdInfo) break;
            offset += infoIdInfo.length;
            const infoSizeInfo = readVint(offset);
            if (!infoSizeInfo) break;
            offset += infoSizeInfo.length;

            // TimecodeScale ID: 0x2AD7B1
            if (infoIdInfo.id === 0x2AD7B1) {
              let scale = 0;
              for (let k = 0; k < infoSizeInfo.value; k++) {
                scale = (scale * 256) + bytes[offset + k];
              }
              if (scale > 0) timecodeScale = scale;
            }
            // Duration ID: 0x4489
            else if (infoIdInfo.id === 0x4489) {
              durationOffset = offset;      // points to first byte of the float payload
              durationSize = infoSizeInfo.value; // 4 = float32, 8 = float64
            }
            offset += infoSizeInfo.value;
          }
          infoBlockEnd = offset; // actual end after parsing
          break;
        } else {
          // Skip non-Info segment children (Cluster, Tracks, etc.)
          if (segSizeInfo.isUnknown) break;
          offset += segSizeInfo.value;
        }
      }
      break;
    } else {
      if (sizeInfo.isUnknown) break;
      offset += sizeInfo.value;
    }
  }

  // Duration is stored in TimecodeScale ticks. timecodeScale is in nanoseconds.
  // timecodeScale=1,000,000 ns → 1ms per tick → durationValue = durationMs ticks
  const durationValue = (durationMs * 1_000_000) / timecodeScale;

  // ── Case A: Duration element exists — force-overwrite it regardless of current value
  if (durationOffset !== -1) {
    if (durationSize === 4) {
      dataView.setFloat32(durationOffset, durationValue, false); // big-endian
    } else if (durationSize === 8) {
      dataView.setFloat64(durationOffset, durationValue, false); // big-endian
    } else {
      // Unexpected size — fall through to null to use npm fallback
      return null;
    }
    return new Blob([bytes], { type: "video/webm" });
  }

  // ── Case B: Duration element is missing — inject it into the Info block and update parent size
  if (infoBlockStart !== -1) {
    const DURATION_ELEMENT_SIZE = 11; // 2-byte ID (0x4489) + 1-byte size (0x88 = VINT for 8) + 8-byte float64
    const newBuffer = new Uint8Array(bytes.length + DURATION_ELEMENT_SIZE);
    
    // Copy everything up to the end of Info content
    newBuffer.set(bytes.slice(0, infoBlockEnd), 0);
    
    // Write the Duration element
    let ins = infoBlockEnd;
    newBuffer[ins++] = 0x44; // Duration ID high byte
    newBuffer[ins++] = 0x89; // Duration ID low byte  (0x4489)
    newBuffer[ins++] = 0x88; // VINT size: 0x88 = VINT size for 8
    
    // Write float64 big-endian
    const tmp = new DataView(newBuffer.buffer);
    tmp.setFloat64(ins, durationValue, false);
    ins += 8;
    
    // Copy remainder of original file
    newBuffer.set(bytes.slice(infoBlockEnd), ins);
    
    // Update the size of the Info container in the new buffer
    // Info ID starts at infoBlockStart. The size VINT starts at infoBlockStart + 4 (Info ID is 4 bytes).
    writeVint(newBuffer, infoBlockStart + 4, infoSizeValue + DURATION_ELEMENT_SIZE, infoSizeLength);
    
    return new Blob([newBuffer], { type: "video/webm" });
  }

  return null; // Could not locate EBML structure or duration element — caller will use npm fallback
}

async function fixDuration(blob, durationMs) {
  if (!blob || blob.size === 0 || !durationMs || durationMs <= 0) {
    return blob;
  }
  try {
    const arrayBuffer = await blob.arrayBuffer();

    // PRIMARY: Custom EBML writer — force-patches regardless of existing duration value.
    // This bypasses fix-webm-duration's "if (existingDuration > 0) return false" guard
    // which causes Chrome's wrong 1–2s header duration to be preserved.
    const fixedBlob = setWebmDuration(arrayBuffer, durationMs);
    if (fixedBlob) {
      console.log(`[FocusRecorder] setWebmDuration patched duration to ${durationMs}ms`);
      return fixedBlob;
    }

    // FALLBACK: npm fix-webm-duration — only works when Chrome did NOT write a duration,
    // which is rare but happens on some browser versions.
    console.warn("[FocusRecorder] setWebmDuration returned null — EBML structure not found, trying npm fallback");
    const fallback = await fixWebmDuration(blob, durationMs, { logger: false });
    return fallback || blob;
  } catch (err) {
    console.warn("[FocusRecorder] fixDuration error:", err);
    return blob;
  }
}

/** Web Worker timer generator for unthrottled 30 FPS background canvas rendering. */
function createTimerWorker(fps = 30) {
  const intervalMs = Math.round(1000 / fps);
  try {
    const workerCode = `
      let intervalId = null;
      self.onmessage = function(e) {
        if (e.data === 'start') {
          clearInterval(intervalId);
          intervalId = setInterval(function() {
            self.postMessage('tick');
          }, ${intervalMs});
        } else if (e.data === 'stop') {
          clearInterval(intervalId);
          intervalId = null;
        }
      };
    `;
    const blob = new Blob([workerCode], { type: "application/javascript" });
    const url = URL.createObjectURL(blob);
    const worker = new Worker(url);
    worker.cleanup = () => {
      try {
        worker.postMessage("stop");
        worker.terminate();
      } catch (e) { }
      URL.revokeObjectURL(url);
    };
    return worker;
  } catch (err) {
    console.warn("[FocusRecorder] Worker creation failed, using main thread fallback:", err);
    return {
      postMessage: () => { },
      cleanup: () => { }
    };
  }
}

export function useRecorder() {
  const _saved = loadSettings();
  const [quality, setQuality] = useState(_saved.recordingQuality ?? "1080p");
  const [fps, setFps] = useState(_saved.fps ?? 30);
  const [micOn, setMicOn] = useState(true);
  const [audioOn, setAudioOn] = useState(true);
  const [camOn, setCamOn] = useState(false);
  const [captureMode, setCaptureMode] = useState("window"); // "window" | "monitor" | "browser"

  const micDeviceIdRef = useRef(_saved.microphoneId ?? "");
  const camDeviceIdRef = useRef(_saved.webcamId ?? "");

  const [status, setStatus] = useState("idle");
  const [elapsed, setElapsed] = useState(0);
  const [error, setError] = useState(null);
  const [warning, setWarning] = useState(null);
  const [camReady, setCamReady] = useState(true);

  const camInitPromiseRef = useRef(null);
  const mediaRecorderRef = useRef(null);
  const chunksRef = useRef([]);
  const displayStreamRef = useRef(null);
  const micStreamRef = useRef(null);
  const camStreamRef = useRef(null);
  const mixedStreamRef = useRef(null);
  const audioCtxRef = useRef(null);
  const canvasRef = useRef(null);
  const timerRef = useRef(null);
  const elapsedRef = useRef(0);
  const previewRef = useRef(null);
  const camVideoRef = useRef(null);
  const pipRectRef = useRef({ x: 0, y: 0, width: 0, height: 0 });
  const rafIdRef = useRef(null);
  const rvfcIdRef = useRef(null);
  const timerWorkerRef = useRef(null);
  const startTimestampRef = useRef(null);
  const recordingStartTimeRef = useRef(null);
  const recordingStopTimeRef = useRef(null); // FIX: exact wall-clock stop time
  const accumulatedMsRef = useRef(0);
  const recordingActiveRef = useRef(false);
  const isStoppingRef = useRef(false);
  const renderVideoRef = useRef(null);
  const canvasVideoTrackRef = useRef(null);

  const fpsRef = useRef(fps);
  const camOnRef = useRef(camOn);
  useEffect(() => { fpsRef.current = fps; }, [fps]);
  useEffect(() => { camOnRef.current = camOn; }, [camOn]);
  useEffect(() => { elapsedRef.current = elapsed; }, [elapsed]);

  // ── Timer ─────────────────────────────────────────────────────────────────
  const startTimer = useCallback(() => {
    clearInterval(timerRef.current);
    startTimestampRef.current = Date.now();
    timerRef.current = setInterval(() => {
      if (startTimestampRef.current !== null) {
        const activeMs = Date.now() - startTimestampRef.current;
        const totalMs = accumulatedMsRef.current + activeMs;
        const totalSecs = Math.floor(totalMs / 1000);
        elapsedRef.current = totalSecs;
        setElapsed(totalSecs);
      }
    }, 200);
  }, []);

  const stopTimer = useCallback(() => {
    if (startTimestampRef.current !== null) {
      const ms = Date.now() - startTimestampRef.current;
      accumulatedMsRef.current += ms;
      startTimestampRef.current = null;
    }
    clearInterval(timerRef.current);
    timerRef.current = null;

    const totalSecs = Math.floor(accumulatedMsRef.current / 1000);
    elapsedRef.current = totalSecs;
    setElapsed(totalSecs);
  }, []);

  // ── Stream helpers ────────────────────────────────────────────────────────
  const stopStreamRef = useCallback((streamRef) => {
    if (streamRef.current) {
      streamRef.current.getTracks().forEach(t => t.stop());
      streamRef.current = null;
    }
  }, []);

  const teardownAllStreams = useCallback(() => {
    recordingActiveRef.current = false;

    if (timerWorkerRef.current) {
      try { timerWorkerRef.current.cleanup(); } catch (e) { }
      timerWorkerRef.current = null;
    }

    if (audioCtxRef.current && audioCtxRef.current.state !== "closed") {
      try { audioCtxRef.current.close(); } catch (e) { console.warn(e); }
      audioCtxRef.current = null;
    }

    if (rafIdRef.current) {
      cancelAnimationFrame(rafIdRef.current);
      rafIdRef.current = null;
    }
    if (renderVideoRef.current) {
      try {
        renderVideoRef.current.pause();
        renderVideoRef.current.srcObject = null;
        if (renderVideoRef.current.parentNode) {
          renderVideoRef.current.parentNode.removeChild(renderVideoRef.current);
        }
      } catch (e) {
        console.warn("Error pausing render video:", e);
      }
      renderVideoRef.current = null;
    }
    stopStreamRef(displayStreamRef);
    stopStreamRef(micStreamRef);
    stopStreamRef(mixedStreamRef);
    if (camStreamRef.current) {
      camStreamRef.current.getTracks().forEach(t => { t.onended = null; t.stop(); });
      camStreamRef.current = null;
    }
    if (previewRef.current) previewRef.current.srcObject = null;
    if (camVideoRef.current) camVideoRef.current.srcObject = null;
    if (canvasRef.current) {
      try {
        const ctx = canvasRef.current.getContext("2d");
        if (ctx) {
          ctx.clearRect(0, 0, canvasRef.current.width, canvasRef.current.height);
        }
      } catch (e) {
        console.warn("Error clearing canvas:", e);
      }
      canvasRef.current = null;
    }
    canvasVideoTrackRef.current = null;
  }, [stopStreamRef]);

  const handleShareEnded = useCallback(() => {
    if (isStoppingRef.current) return;
    isStoppingRef.current = true;

    console.log("[FocusRecorder] Stopping recording & flushing buffers...");
    // FIX: Capture exact stop time before stopTimer() so onstop gets precise durationMs
    recordingStopTimeRef.current = Date.now();
    stopTimer();

    if (mediaRecorderRef.current && mediaRecorderRef.current.state !== "inactive") {
      try {
        if (mediaRecorderRef.current.requestData) {
          mediaRecorderRef.current.requestData();
        }
        mediaRecorderRef.current.stop();
      } catch (e) {
        console.warn("Error stopping media recorder:", e);
        teardownAllStreams();
        setStatus("idle");
        isStoppingRef.current = false;
      }
    } else {
      teardownAllStreams();
      setStatus("idle");
      isStoppingRef.current = false;
    }
  }, [stopTimer, teardownAllStreams]);

  // ── Webcam startup ────────────────────────────────────────────────────────
  const startCamStream = useCallback(async () => {
    const vid = camDeviceIdRef.current;
    const mic = micDeviceIdRef.current;
    const targetFps = fpsRef.current || 30;
    const audioCon = mic ? { deviceId: { exact: mic } } : true;

    const tryGet = async (constraints) => navigator.mediaDevices.getUserMedia(constraints);

    try {
      return await tryGet({
        video: vid
          ? { deviceId: { ideal: vid }, width: { ideal: 1920 }, height: { ideal: 1080 }, frameRate: { ideal: targetFps } }
          : { width: { ideal: 1280 }, height: { ideal: 720 }, frameRate: { ideal: targetFps }, facingMode: "user" },
        audio: audioCon,
      });
    } catch {
      return await tryGet({ video: true, audio: true }).catch(() => tryGet({ video: true }));
    }
  }, []);

  const attachAndWatchCamRef = useRef(null);
  const attachAndWatchCam = useCallback((stream) => {
    camStreamRef.current = stream;
    const vid = camVideoRef.current;
    if (vid) {
      vid.srcObject = stream;
      vid.play().catch(e => console.warn("Webcam play blocked:", e.message));
    }
    stream.getVideoTracks().forEach(track => {
      track.onended = () => {
        if (!camStreamRef.current) return;
        startCamStream()
          .then(s => attachAndWatchCamRef.current?.(s))
          .catch(() => { if (camVideoRef.current) camVideoRef.current.srcObject = null; });
      };
    });
  }, [startCamStream]);

  useEffect(() => { attachAndWatchCamRef.current = attachAndWatchCam; }, [attachAndWatchCam]);

  useEffect(() => {
    if (camOn) {
      setCamReady(false);
      let resolveInit;
      camInitPromiseRef.current = new Promise(r => { resolveInit = r; });
      startCamStream()
        .then(stream => {
          attachAndWatchCam(stream);
          setCamReady(true);
          resolveInit();
        })
        .catch(err => {
          setCamOn(false);
          setCamReady(true);
          resolveInit();
          setError(err.name === "NotAllowedError"
            ? "Camera permission denied. Allow access and try again."
            : `Camera error: ${err.message}`);
        });
    } else {
      if (camStreamRef.current) {
        camStreamRef.current.getTracks().forEach(t => { t.onended = null; t.stop(); });
        camStreamRef.current = null;
      }
      if (camVideoRef.current) camVideoRef.current.srcObject = null;
      setCamReady(true);
      camInitPromiseRef.current = null;
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [camOn]);

  // ── startRecording ────────────────────────────────────────────────────────
  const startRecording = useCallback(async () => {
    setError(null);
    setWarning(null);
    setStatus("requesting");
    isStoppingRef.current = false;
    accumulatedMsRef.current = 0;
    elapsedRef.current = 0;
    setElapsed(0);
    startTimestampRef.current = null;
    recordingStartTimeRef.current = null;
    recordingStopTimeRef.current = null;

    try {
      const targetFps = fps || 30;
      const qConfig = QUALITY_MAP[quality] || QUALITY_MAP["1080p"];
      const { width, height, bitrate: videoBitrate } = qConfig;

      if (camOn && camInitPromiseRef.current) {
        await camInitPromiseRef.current;
      }

      // ── 1. Get screen/window capture ─────────────────────────────────────
      console.log(`[FocusRecorder] Requesting screen capture (mode: ${captureMode}, targetFps: ${targetFps})...`);
      let displayStream;
      try {
        const displayOptions = {
          video: {
            displaySurface: captureMode,
            width: { ideal: width },
            height: { ideal: height },
            frameRate: { ideal: targetFps, max: targetFps }
          },
          audio: audioOn ? {
            autoGainControl: false,
            echoCancellation: false,
            noiseSuppression: false,
            systemAudio: "include"
          } : false,
          selfBrowserSurface: "exclude",
          surfaceSwitching: "include"
        };
        displayStream = await navigator.mediaDevices.getDisplayMedia(displayOptions);
      } catch (screenErr) {
        if (
          screenErr.name === "NotAllowedError" ||
          screenErr.name === "AbortError" ||
          screenErr.name === "PermissionDeniedError"
        ) {
          setStatus("idle");
          return;
        }
        if (audioOn && screenErr.name !== "NotAllowedError") {
          try {
            displayStream = await navigator.mediaDevices.getDisplayMedia({
              video: {
                displaySurface: captureMode,
                width: { ideal: width },
                height: { ideal: height },
                frameRate: { ideal: targetFps, max: targetFps }
              },
              audio: false
            });
            setWarning("System audio unavailable for this window. Recording video + microphone audio.");
          } catch (retryErr) {
            if (
              retryErr.name === "NotAllowedError" ||
              retryErr.name === "AbortError" ||
              retryErr.name === "PermissionDeniedError"
            ) {
              setStatus("idle");
              return;
            }
            throw retryErr;
          }
        } else {
          throw screenErr;
        }
      }

      console.log("[FocusRecorder] Screen permission granted");
      if (!displayStream.active || displayStream.getVideoTracks().length === 0) {
        throw new Error("Display stream is not active after getDisplayMedia.");
      }
      displayStreamRef.current = displayStream;

      // ── 2. Web Audio API Mixing for System Audio + Microphone ──────────────
      const rawAudioTracks = [];
      const systemAudioTracks = displayStream.getAudioTracks();
      let micAudioTracks = [];

      if (micOn) {
        if (camStreamRef.current && camStreamRef.current.getAudioTracks().length > 0) {
          micAudioTracks = camStreamRef.current.getAudioTracks();
        } else {
          try {
            const micCon = micDeviceIdRef.current
              ? { audio: { deviceId: { exact: micDeviceIdRef.current } }, video: false }
              : { audio: true, video: false };
            const micStream = await navigator.mediaDevices.getUserMedia(micCon);
            micStreamRef.current = micStream;
            micAudioTracks = micStream.getAudioTracks();
          } catch (micErr) {
            console.warn("Mic unavailable:", micErr.message);
            setWarning(`Microphone unavailable: ${micErr.message}. Recording without mic.`);
          }
        }
      }

      let mixedAudioTrack = null;

      const hasSysAudio = systemAudioTracks.length > 0;
      const hasMicAudio = micAudioTracks.length > 0;

      if (hasSysAudio && hasMicAudio) {
        // Dual sources: must mix via AudioContext
        try {
          const audioCtx = new (window.AudioContext || window.webkitAudioContext)();
          audioCtxRef.current = audioCtx;
          if (audioCtx.state === "suspended") {
            await audioCtx.resume();
          }
          const dest = audioCtx.createMediaStreamDestination();
          const sysSource = audioCtx.createMediaStreamSource(new MediaStream([systemAudioTracks[0]]));
          const micSource = audioCtx.createMediaStreamSource(new MediaStream([micAudioTracks[0]]));
          sysSource.connect(dest);
          micSource.connect(dest);
          // Keep refs on .current to prevent V8 GC from disconnecting AudioContext nodes.
          // BUG FIX: Was audioCtxRef._sysSource (attaches to the ref wrapper object, not .current)
          // which does NOT prevent GC — nodes could be collected mid-recording, silencing mic.
          audioCtxRef.current._sysSource = sysSource;
          audioCtxRef.current._micSource = micSource;
          mixedAudioTrack = dest.stream.getAudioTracks()[0];
          if (mixedAudioTrack) rawAudioTracks.push(mixedAudioTrack);
        } catch (mixErr) {
          console.warn("[FocusRecorder] AudioContext mixing fallback:", mixErr);
          rawAudioTracks.push(systemAudioTracks[0]);
          rawAudioTracks.push(micAudioTracks[0]);
        }
      } else if (hasSysAudio) {
        // Single system audio — attach directly, no AudioContext clock offset
        rawAudioTracks.push(systemAudioTracks[0]);
      } else if (hasMicAudio) {
        // Single mic audio — attach directly, no AudioContext clock offset
        rawAudioTracks.push(micAudioTracks[0]);
      }

      // ── 3. Attach preview video ───────────────────────────────────────────
      if (previewRef.current) {
        previewRef.current.srcObject = displayStream;
        previewRef.current.play().catch(e => console.warn("[FocusRecorder] Preview play():", e.message));
      }

      // ── 4. Direct Screen Stream vs Canvas Compositing ─────────────────────
      let combinedStream;

      const requiresCanvas = camOn;

      if (!requiresCanvas) {
        console.log("[FocusRecorder] Using direct native stream (Webcam PIP OFF)");
        const displayVideoTrack = displayStream.getVideoTracks()[0];
        combinedStream = new MediaStream([displayVideoTrack, ...rawAudioTracks]);
        mixedStreamRef.current = combinedStream;
      } else {
        console.log(`[FocusRecorder] Setting up canvas compositing (Webcam PIP: ${camOn})...`);

        const renderVideo = document.createElement("video");
        renderVideo.srcObject = displayStream;
        renderVideo.muted = true;
        renderVideo.playsInline = true;
        renderVideo.style.position = "fixed";
        renderVideo.style.top = "0";
        renderVideo.style.left = "0";
        renderVideo.style.width = "1px";
        renderVideo.style.height = "1px";
        renderVideo.style.zIndex = "999999";
        renderVideo.style.opacity = "1";
        renderVideo.style.pointerEvents = "none";
        document.body.appendChild(renderVideo);

        renderVideoRef.current = renderVideo;
        await renderVideo.play().catch(e => console.warn("[FocusRecorder] Render video play():", e.message));

        const canvasW = renderVideo.videoWidth || width;
        const canvasH = renderVideo.videoHeight || height;

        const canvas = document.createElement("canvas");
        canvas.width = canvasW;
        canvas.height = canvasH;
        canvasRef.current = canvas;
        const ctx = canvas.getContext("2d");

        let togglePixel = false;
        const renderCanvas = () => {
          const rVideo = renderVideoRef.current;
          if (rVideo && (rVideo.readyState >= 1 || rVideo.videoWidth > 0)) {
            if (rVideo.videoWidth > 0 && rVideo.videoHeight > 0 && (canvas.width !== rVideo.videoWidth || canvas.height !== rVideo.videoHeight)) {
              canvas.width = rVideo.videoWidth;
              canvas.height = rVideo.videoHeight;
            }
            try {
              ctx.drawImage(rVideo, 0, 0, canvas.width, canvas.height);
            } catch (e) { }
          }

          togglePixel = !togglePixel;
          ctx.fillStyle = togglePixel ? "rgba(0,0,0,0.01)" : "rgba(255,255,255,0.01)";
          ctx.fillRect(0, 0, 1, 1);

          const camVid = camVideoRef.current;
          if (camOnRef.current && camVid && camVid.readyState >= 2) {
            let rect = pipRectRef.current;
            if (!rect || rect.width <= 0 || rect.height <= 0) {
              const pipW_px = 240;
              const pipH_px = 135;
              rect = {
                x: Math.max(0, (canvas.width - pipW_px - 20) / canvas.width),
                y: Math.max(0, (canvas.height - pipH_px - 20) / canvas.height),
                width: pipW_px / canvas.width,
                height: pipH_px / canvas.height
              };
            }

            const pipX = rect.x * canvas.width;
            const pipY = rect.y * canvas.height;
            const pipW = rect.width * canvas.width;
            const pipH = rect.height * canvas.height;

            const cW = camVid.videoWidth || 1;
            const cH = camVid.videoHeight || 1;
            const cA = cW / cH;
            const pA = pipW / pipH;

            let sx = 0, sy = 0, sw = cW, sh = cH;
            if (cA > pA) {
              sw = cH * pA;
              sx = (cW - sw) / 2;
            } else {
              sh = cW / pA;
              sy = (cH - sh) / 2;
            }

            ctx.save();
            ctx.beginPath();
            if (ctx.roundRect) ctx.roundRect(pipX, pipY, pipW, pipH, 16);
            else ctx.rect(pipX, pipY, pipW, pipH);
            ctx.clip();
            ctx.drawImage(camVid, sx, sy, sw, sh, pipX, pipY, pipW, pipH);
            ctx.restore();

            ctx.save();
            ctx.beginPath();
            if (ctx.roundRect) ctx.roundRect(pipX, pipY, pipW, pipH, 16);
            else ctx.rect(pipX, pipY, pipW, pipH);
            ctx.strokeStyle = "rgba(168,85,247,0.5)";
            ctx.lineWidth = 4;
            ctx.stroke();
            ctx.restore();
          }

          if (canvasVideoTrackRef.current && typeof canvasVideoTrackRef.current.requestFrame === "function") {
            try { canvasVideoTrackRef.current.requestFrame(); } catch (e) { }
          }
        };

        recordingActiveRef.current = true;

        const timerWorker = createTimerWorker(targetFps);
        timerWorkerRef.current = timerWorker;
        timerWorker.onmessage = () => {
          if (recordingActiveRef.current) renderCanvas();
        };
        timerWorker.postMessage("start");

        const canvasStream = canvas.captureStream(0);
        const canvasVideoTrack = canvasStream.getVideoTracks()[0];
        canvasVideoTrackRef.current = canvasVideoTrack;
        combinedStream = new MediaStream([canvasVideoTrack, ...rawAudioTracks]);
        mixedStreamRef.current = combinedStream;
      }

      // ── 5. MediaRecorder Setup & Continuous Chunk Collection ──────────────
      chunksRef.current = [];
      const hasAudio = rawAudioTracks.length > 0;
      const mimeType = getBestMimeType(hasAudio);
      const recorderOptions = {
        mimeType: mimeType || undefined,
        videoBitsPerSecond: videoBitrate,
        audioBitsPerSecond: 128_000,
      };

      console.log(`[FocusRecorder] Starting MediaRecorder: ${quality} (${videoBitrate / 1e6} Mbps), MIME: ${mimeType}, Has Audio: ${hasAudio}`);

      const recorder = new MediaRecorder(combinedStream, recorderOptions);
      mediaRecorderRef.current = recorder;

      // Collect ALL video/audio chunks as they arrive
      recorder.ondataavailable = (e) => {
        if (e.data && e.data.size > 0) {
          chunksRef.current.push(e.data);
        }
      };

      // Create video Blob ONLY inside MediaRecorder.onstop after complete finish
      recorder.onstop = async () => {
        console.log("[FocusRecorder] MediaRecorder.onstop fired — constructing final video file...");
        setStatus("saving");
        try {
          const startTime = recordingStartTimeRef.current || Date.now();
          // Use the wall-clock stop time captured at the exact moment stop() was requested,
          // NOT Date.now() here — onstop fires asynchronously after a variable delay.
          const stopTime = recordingStopTimeRef.current || Date.now();
          const wallClockMs = Math.max(0, stopTime - startTime);

          const rawBlob = new Blob(chunksRef.current, { type: mimeType || "video/webm" });
          const arrayBuffer = await rawBlob.arrayBuffer();

          // PRIMARY: The active recording timer — accumulated only during active recording,
          // pause-aware, finalized by stopTimer() before onstop fires.
          const activeRecordingMs = accumulatedMsRef.current;

          // FALLBACK: WebM cluster analysis (may be inaccurate for Chrome recordings)
          const realDurationMs = getWebmDurationFromClusters(arrayBuffer);

          // Priority: active timer > WebM clusters > wall clock (wall clock includes pauses)
          const durationMs = activeRecordingMs > 0
            ? activeRecordingMs
            : realDurationMs > 0
              ? realDurationMs
              : wallClockMs;

          console.log(`[FocusRecorder] Total Chunks: ${chunksRef.current.length}, Raw Size: ${formatBytes(rawBlob.size)}, Exact Duration: ${durationMs}ms`);

          // Patch WebM header EBML duration metadata using proper Promise wrapper around fix-webm-duration
          const finalBlob = await fixDuration(rawBlob, durationMs);
          console.log(`[FocusRecorder] Fixed WebM Blob Size: ${formatBytes(finalBlob.size)}`);

          const durationSecs = Math.round(durationMs / 1000);
          const durationStr = formatTime(durationSecs);
          const date = new Date().toLocaleDateString("en-US", { month: "short", day: "numeric", year: "numeric" });
          const sizeStr = formatBytes(finalBlob.size);
          const tagMode = captureMode === "window" ? "Window" : captureMode === "browser" ? "Tab" : "Screen";
          const title = `${tagMode} Recording — ${date}`;

          await saveRecording({ title, blob: finalBlob, duration: durationStr, date, size: sizeStr, tag: tagMode });
          console.log(`[FocusRecorder] Saved video (${durationStr}, ${sizeStr}) successfully.`);

          const url = URL.createObjectURL(finalBlob);
          const a = document.createElement("a");
          a.href = url;
          a.download = `focusrecorder-${Date.now()}.webm`;
          a.click();
          setTimeout(() => URL.revokeObjectURL(url), 60_000);
          setStatus("completed");
        } catch (saveErr) {
          console.error("[FocusRecorder] Save failed:", saveErr);
          setError(`Failed to save recording: ${saveErr.message}`);
          setStatus("idle");
        } finally {
          teardownAllStreams();
          setCamOn(false);
          isStoppingRef.current = false;
        }
      };

      // Handle browser "Stop sharing" bar click
      const displayTrack = displayStream.getVideoTracks()[0];
      displayTrack.addEventListener("ended", handleShareEnded);

      // FIX: 100ms timeslices - prevents up to 1s of data loss at cluster boundaries
      recordingStartTimeRef.current = Date.now();
      recorder.start(100);
      console.log("[FocusRecorder] MediaRecorder started!");

      setStatus("recording");
      startTimer();

    } catch (err) {
      console.error("[FocusRecorder] startRecording failed:", err.name, err.message, err);
      stopTimer();
      teardownAllStreams();
      if (
        err.name === "NotAllowedError" ||
        err.name === "PermissionDeniedError" ||
        err.name === "AbortError"
      ) {
        setError(null);
      } else if (err.name === "NotSupportedError") {
        setError("Screen recording is not supported in this browser. Use Chrome or Edge.");
      } else {
        setError(`Recording failed: ${err.message}`);
      }
      setStatus("idle");
    }
  }, [quality, fps, micOn, audioOn, camOn, captureMode, startTimer, stopTimer, teardownAllStreams, handleShareEnded]);

  // ── pauseRecording ────────────────────────────────────────────────────────
  const pauseRecording = useCallback(() => {
    if (mediaRecorderRef.current?.state === "recording") {
      mediaRecorderRef.current.pause();
      stopTimer();
      setStatus("paused");
    }
  }, [stopTimer]);

  // ── resumeRecording ───────────────────────────────────────────────────────
  const resumeRecording = useCallback(() => {
    if (mediaRecorderRef.current?.state === "paused") {
      mediaRecorderRef.current.resume();
      startTimer();
      setStatus("recording");
    }
  }, [startTimer]);

  // ── stopRecording ─────────────────────────────────────────────────────────
  const stopRecording = useCallback(() => {
    handleShareEnded();
  }, [handleShareEnded]);

  // ── Cleanup on unmount ────────────────────────────────────────────────────
  useEffect(() => {
    const camVid = camVideoRef.current;
    return () => {
      stopTimer();
      recordingActiveRef.current = false;
      teardownAllStreams();
      if (camStreamRef.current) {
        camStreamRef.current.getTracks().forEach(t => { t.onended = null; t.stop(); });
        camStreamRef.current = null;
      }
      if (camVid) camVid.srcObject = null;
      if (mediaRecorderRef.current?.state !== "inactive") {
        mediaRecorderRef.current?.stop();
      }
    };
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  return {
    status,
    elapsed,
    formattedTime: formatTime(elapsed),
    previewRef,
    camVideoRef,
    error,
    warning,
    camReady,
    captureMode, setCaptureMode,
    quality, setQuality,
    fps, setFps,
    micOn, setMicOn,
    audioOn, setAudioOn,
    camOn, setCamOn,
    startRecording,
    pauseRecording,
    resumeRecording,
    stopRecording,
    setPipRect: (rect) => { pipRectRef.current = rect; },
  };
}
